spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/learn_run_comment

  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    root: INFO
    feign: DEBUG