spring:
  data:
    mongodb:
      uri: ${MONGODB_URI_COMMENT}

  kafka:
    bootstrap-servers: ${EC2_INFRA_HOST}:10000,${EC2_INFRA_HOST}:10001,${EC2_INFRA_HOST}:10002

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka