version: '3.8'

services:
  openvidu-service:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/learn-run/openvidu-service:latest
    container_name: openvidu-service
    ports:
      - 9999:8080
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true
