version: '3.8'

services:
  bookmark-service:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/learn-run/bookmark-service:latest
    container_name: bookmark-service
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true